### ISSUE TITLE
No user with the username

### ISSUE THREAD

**Issue by Inf3ct3d1337** [ThaisenPM/Cheat-Loader-CSGO#12]
So, I've set every up right but when I start the launcher and try to login the usercheck_get.php says No user with the username XY, so I guess I have to add the usernames and the hwid's somewhere in my database, but where and how? :P

**Comment by Inf3ct3d1337** [comment]
Ah, I'm fucking stupid xD, I figured out where I have to add the hwid's in the database, but I still get the error that the username doesn't exist

**Comment by ThaisenPM** [comment]
Don't use v1
