### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by DesmenNarco** [ThaisenPM/Cheat-Loader-CSGO#2]
When i login i get this error
https://gyazo.com/47d32af6a476af834e9334c1ea702d26

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at NovaHook.Form1.Button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2101.1 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Nova Hook
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/loader.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1649.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by ThaisenPM** [comment]
You have to change the program to use your MyBB forums. That error means you didn't do this correctly. Did you follow the instructions I listed or did you just compile and try to run it?

**Comment by DesmenNarco** [comment]
Do you think it is a problem with 000webhost? if so do you have any recommendations for hosting?

**Comment by ThaisenPM** [comment]
I personally use Hosting24.com. When you're registering, use the code 1CENT XD The first month costs 1 cent so not much worry of a loss there

**Comment by ThaisenPM** [comment]
Actually, link me your forums really quick and I can check it out

**Comment by DesmenNarco** [comment]
http://desmen19.000webhostapp.com/

**Comment by ThaisenPM** [comment]
Are you pointing the login script to https://desmen19.000webhostapp.com/member.php?action=login and not just https://desmen19.000webhostapp.com

**Comment by DesmenNarco** [comment]
Yes

**Comment by ThaisenPM** [comment]
Do you still get that error after adding that line?

**Comment by DesmenNarco** [comment]
Yes that error pops up still but now it will also pop up with wrong username and password

**Comment by ThaisenPM** [comment]
Okay so were getting somewhere. Add these 2 lines directly below the WebBrowser1 line
`
WebBrowser2.Navigate("https://desmen19.000webhostapp.com/usercheck.php")
WebBrowser3.Navigate("https://desmen19.000webhostapp.com/hwid.php")
`

**Comment by ThaisenPM** [comment]
I also forgot to add this, go to Form2.vb and add these lines

`
    Private Sub Form2_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        WebBrowser1.Navigate("https://desmen19.000webhostapp.com/member.php?action=login")
    End Sub
`

**Comment by ThaisenPM** [comment]
`Always getting "Password incorrect" while entering the correct password? Click the "having trouble" button and sign in and MAKE SURE you click "Remember me"`

Also an issue that needs fixing

**Comment by DesmenNarco** [comment]
ok after i did that it showed the error again and now the login button is grayed out

**Comment by DesmenNarco** [comment]
But when i click the having trouble button it says i have to wait 14 minutes so that might be why

**Comment by ThaisenPM** [comment]
Hmm, the login button should not stay grayed out. It is supposed to do that for a short bit during the login sequence then return to normal. Do you have Discord so we can continue discussing this there?

**Comment by DesmenNarco** [comment]
Yes i do, Desmen#8355

**Comment by ThaisenPM** [comment]
Issue resolved: 000webhost was blocking the usercheck_get.php file
