### ISSUE TITLE
"User is not premium"

### ISSUE THREAD

**Issue by mejdz** [ThaisenPM/Cheat-Loader-CSGO#3]
How can I give some user premium rights?

**Comment by mejdz** [comment]
I'm stupid lol.. it was obvious

But I get this error when I'm trying to login
https://image.prntscr.com/image/Be_b7cZLSCqaS9XnEi21Zw.png (Also HWID function not setup right)
And this is my hwid_get configuration (same for usercheck_get) https://image.prntscr.com/image/zZjQ3PklSAamYw2yGYIm5g.png

I can't figure out why i still get these errors, all those informations about database are correct.. Even when I'm trying to open ../usercheck_get.php through my browser i get "This page isn’t working", it's confusing cause I can open usercheck.php and hwid.php..

Hope you guys can somehow help me

**Comment by mejdz** [comment]
![Image](https://image.prntscr.com/image/zZjQ3PklSAamYw2yGYIm5g.png)

**Comment by ThaisenPM** [comment]
Form1 and Form3
