### ISSUE TITLE
Dll injection

### ISSUE THREAD

**Issue by mejdz** [ThaisenPM/Cheat-Loader-CSGO#4]
Why when i try to inject my "Main" cheat from hosting this "waiting for csgo.exe" window just shut down without any "Succesfully injected" message?

I have my cheat uploaded in htdoc, and i changed everything here
https://image.prntscr.com/image/vQwnwLw1SlmrEVJiS8gPsg.png

Also when I click "Inject" and look at \dll folder, it shows just some random named 1kb .dll files?

**Comment by ThaisenPM** [comment]
DLL injection doesn't work correctly. It's an easy fix, not gonna fix it globally

**Comment by mejdz** [comment]
and you will not tell us noobies how? haha

**Comment by Brodys** [comment]
@ThaisenPM could you please help me get the injector working. I'm just trying to make a community based forums. After a few things get fixed i'll be able to help players get cheats for hacks released on hackforums and unknowncheats.
