### ISSUE TITLE
Injection Failed

### ISSUE THREAD

**Issue by timmy473** [ThaisenPM/Cheat-Loader-CSGO#9]
The DLL Download Workshop bitte the injection Not ?! And why you build in Same fails ?!

**Comment by GermanKingYT** [comment]
yeah too need help please

**Comment by ThaisenPM** [comment]
I broke the LoadLib injector on purpose. Have fun fixing it

**Comment by Brodys** [comment]
Oh you broke the injector, that explains it... i have been fiddling with this for hours!!!! could i get it working again? Trying to get a community based cheat loader going for newbs
